services:
    forumhulp.exportimportusers.listener:
        class: forumhulp\exportimportusers\event\listener
        arguments:
            - @controller.helper
        tags:
            - { name: event.listener }